esphome:
  name: emporia-vue-utility

  devices:
    - id: smart_meter_reader
      name: "Meter"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  source:
    type: git
    url: https://github.com/nekorevend/esphome-emporia-vue-utility

# Enable logging
logger:

# Enable Home Assistant API
# Encryption secures it.  Any password will work.  See FAQ.
api:
  encryption:
    key: "blah"

# Secures OTA Updates.  Any password will work.  See FAQ.
ota:
  platform: esphome
  password: "blah"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Runs a webserver on http://emporia-vue-utility.local with no password
web_server:
  port: 80
# Optionally define a username + password
#  auth:
#    username: 'glen'
#    password: 'vue_password'

# This uart connects to the MGM111
uart:
  id: emporia_uart
  rx_pin: GPIO21
  tx_pin: GPIO22
  baud_rate: 115200

sensor:
  - platform: emporia_vue_utility
    uart_id: emporia_uart
    debug: true
    update_interval: 15s
    power:
      name: "Watts"
      device_id: smart_meter_reader
    energy:
      name: "Wh Net"
      device_id: smart_meter_reader
    energy_export:
      name: "Wh Returned"
      device_id: smart_meter_reader
    energy_import:
      name: "Wh Consumed"
      device_id: smart_meter_reader

# This LED is marked D3 on the pcb and is the power led on the case
status_led:
  pin:
    number: GPIO25
    # It *is* inverted, but being normally on looks better
    inverted: false
